### PR TITLE
fix(protonvpn): authenticated servers data updating

### LINKED ISSUE #2820: Bug: protonvpn servers update broken? 400 Bad Request
### Is this urgent?

Yes

### Host OS

Unraid

### CPU arch

x86_64

### VPN service provider

ProtonVPN

### What are you using to run the container

docker-compose

### What is the version of Gluetun

Running version latest built on 2025-01-22T08:30:14.628Z (commit 13532c8)

### What's the problem 🤔

Tried to run:

```docker run --rm -v /mnt/cache/appdata/gluetun:/gluetun ghcr.io/qdm12/gluetun update -enduser -providers protonvpn```

But get a Bad Request Error

### Share your logs (at least 10 lines)

```plain text
2025-06-04T22:31:32Z INFO merging by most recent 20776 hardcoded servers and 20776 servers read from /gluetun/servers.json
2025-06-04T22:31:33Z INFO updating Protonvpn servers...
2025-06-04T22:31:33Z ERROR updating server information: getting servers: HTTP status code not OK: 400 400 Bad Request
2025-06-04T22:31:33Z INFO Shutdown successful
```

### Share your configuration

```yml
gluetun:
    container_name: gluetun
    image: ghcr.io/qdm12/gluetun:latest
    labels:
      net.unraid.docker.managed: 'composeman'
      net.unraid.docker.icon: 'https://static-00.iconduck.com/assets.00/vpn-icon-1863x2048-b1dwlnad.png'
      net.unraid.docker.webui: ''
      net.unraid.docker.shell: ''
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /mnt/user/appdata/gluetun:/gluetun
    environment:
      - TZ=${TZ}
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - PORT_FORWARD_ONLY=on
      - VPN_PORT_FORWARDING=on
      - SERVER_COUNTRIES=Belgium
```

### PR DESCRIPTION
**Pull request by qdm12**
- `-proton-username` flag for cli update
- `-proton-password` flag for cli update
- `UPDATER_PROTONVPN_USERNAME` option for periodic updates
- `UPDATER_PROTONVPN_PASSWORD` option for periodic updates

Fix #2820 

Clone of #2789 but with a branch within the repository, so other forks can target it (#2864)

### CODE REVIEW

**Comment by kubrickfr** [comment]
Does this require any new settings? It doesn't look like it but it doesn't seem to work, at least for me.

`ERROR updating server information: getting servers: HTTP status code not OK: 403 403 Forbidden`

**Comment by qdm12** [comment]
This is unfinished and I'm waiting for an answer at: https://github.com/qdm12/gluetun/pull/2864#issuecomment-3233067587

Actually if you want to help, maybe you could try on your side (I don't have a protonvpn account), for example with curl, this is what's done currently in the Go code:

```
curl -X POST https://api.proton.me/auth/v4/sessions -H "Content-Type: application/json" -H "x-pm-appversion: Other" -H "x-pm-apiversion: 3" -H "User-Agent: test" -d '{"Scope": "vpn"}'
```

Now the json body can also contain a `ClientSecret` string and a `Payload` string and I have no idea what these are.

This returns you an `AccessToken` and a `UID`, which you can then use to access https://api.proton.me/vpn/v1/logicals:

```
curl -X GET https://api.proton.me/vpn/v1/logicals -H "Authorization: Bearer <AccessToken>" -H "x-pm-uid: <UID>" -H "x-pm-appversion: Other" -H "x-pm-apiversion: 3" -H "User-Agent: test"
```

Obviously something isn't right in  one or the other or both of these commands. If you can crack this, I can near-immediately fix Gluetun.

**Comment by Drewsapple** [comment]
I tried to figure out the auth flow with `curl` for a bit and resorted to using their python packages instead. Annoyingly, I think they're only packaged for their debian releases, so I built a container that sets them up and runs a simple script to auth and then fetch the server list. I spent some time trying to inspect the requests made and copy them, but that's not something I've done before and felt I was at a dead end. 

You can find the repo for the container [here](https://github.com/Drewsapple/protonvpn-helper), it's worked to generate the server list files for me. If you want to try and inspect the requests, my work for that was in the [instrumented](https://github.com/Drewsapple/protonvpn-helper/tree/instrumented) branch, although it's all just stuff GPT5 wrote. I hope this is helpful for someone else who has more experience reversing apis.

**Comment by kubrickfr** [comment]
So far, the only way I have found if you want to get _all_ the servers including premium is to go on https://account.proton.me/vpn, log-in, get the value of the `REFRESH-` cookie, which contains a URL-encoded value like

`{"ResponseType":"token","ClientID":"WebAccount","GrantType":"refresh_token","RefreshToken":"xxxx","UID":"yyy"}`

It's valid for a year.

Then you can query `https://account.proton.me/api/auth/refresh` like so

```
  curl 'https://account.proton.me/api/auth/refresh' \
  --compressed \
  -X POST \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:142.0) Gecko/20100101 Firefox/142.0' \
  -H 'Accept: application/vnd.protonmail.v1+json' \
  -H 'Accept-Language: en-GB,en-US;q=0.7,en;q=0.3' \
  -H 'Accept-Encoding: gzip, deflate, br, zstd' \
  -H 'Referer: https://account.proton.me/u/1/vpn/WireGuard' \
  -H 'x-pm-appversion: web-account@5.0.285.0' \
  -H 'x-pm-uid: yyy' \
  -H 'Origin: https://account.proton.me' \
  -H 'Cookie: REFRESH-yyy=%7B%22ResponseType%22%3A%22token%22%2C%22ClientID%22%3A%22WebAccount%22%2C%22GrantType%22%3A%22refresh_token%22%2C%22RefreshToken%22%3A%xxxx%22%2C%22UID%22%3A%yyy%22%7D;' \
```

replacing xxxx and yyy with the appropriate value, with that you get a cookie named `AUTH-yyy=zzzz` and query

```
curl 'https://account.proton.me/api/vpn/logicals' \
  --compressed \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:142.0) Gecko/20100101 Firefox/142.0' \
  -H 'Accept: application/vnd.protonmail.v1+json' \
  -H 'Accept-Language: en-GB,en-US;q=0.7,en;q=0.3' \
  -H 'Accept-Encoding: gzip, deflate, br, zstd' \
  -H 'Referer: https://account.proton.me/u/1/vpn/WireGuard' \
  -H 'x-pm-appversion: web-account@5.0.285.0' \
  -H 'x-pm-uid: yyy' \
  -H 'Connection: keep-alive' \
  -H 'Cookie: AUTH-yyy=zzzz;'
```

But I would _really_ not like to have to do this because I'm pretty sure that if for any reason this token leaks, then whoever gets it can control my account.

**Comment by qdm12** [comment]
I worked like 12 hours on it the last 2 days with just failures, I sent proton support an email at the end of the day, because their authentication system is just plain odd 🤷  The even have https://github.com/ProtonMail/go-proton-api which I twisted in all ways possible without succeeding once... 😢 
What I'll do tomorrow though, is just use some token from my browser (thanks for the comment @kubrickfr !) to update the servers in Gluetun on the master branch. Updater will remain broken for a few more days/weeks until their authentication mechanism can finally be understood though.

**Comment by qdm12** [comment]
Ok I finally figured it out @kubrickfr - your curl commands definitely helped me out a lot get started so thanks for that 💪 !
Proton has been unhelpful as hell and I'm mad at them.
But given I'm stubborn enough, username+password authentication finally works (a good 20 hours of work ugh) to update servers data. I didn't work on 2fa at this time, because I'm sure it's many more hours of reverse engineering which can be skipped, at least there is a way to update servers now.
It does import protonmail/go-srp but I really don't want to reinvent the wheel, especially since this is really specific code to proton, I think it's wise for this one time to just import that.

File: internal/configuration/settings/updater.go [hunk 1]
```diff
@@ -51,17 +56,30 @@ func (u Updater) Validate() (err error) {
...
+		if provider == providers.Protonvpn {
+			switch {
+			case *u.ProtonUsername == "":
+				return fmt.Errorf("%w for provider %s",
+					ErrUpdaterProtonUsernameMissing, providers.Protonvpn)
+			case *u.ProtonPassword == "":
+				return fmt.Errorf("%w for provider %s",
+					ErrUpdaterProtonPasswordMissing, providers.Protonvpn)
+			}
+		}
```
Comment (qdm12) [inline internal/configuration/settings/updater.go:70]: I don't think this should be a requirement. Most people don't run the updater periodically I think. Instead let's have a check when updating and log out a warning stating we will skip the update because no credentials were set.

File: internal/provider/protonvpn/updater/api.go [hunk 2]
```diff
@@ -33,35 +483,33 @@ type physicalServer struct {
...
 }
 
-func fetchAPI(ctx context.Context, client *http.Client) (
+func (c *apiClient) fetchServers(ctx context.Context, cookie cookie) (
 	data apiData, err error,
 ) {
-	const url = "https://api.protonmail.ch/vpn/logicals"
-
+	const url = "https://account.proton.me/api/vpn/logicals"
+	// Old Logicals API endpoint: https://api.protonmail.ch/vpn/logicals
```
Comment (qdm12) [inline internal/provider/protonvpn/updater/api.go]:
```suggestion
```

File: internal/provider/protonvpn/updater/types.go [hunk 3]
```diff
@@ -0,0 +1,86 @@
...
+	Code         uint     `json:"Code"`         // 1000 on success
+	AccessToken  string   `json:"AccessToken"`  // 32-chars lowercase and digits
+	RefreshToken string   `json:"RefreshToken"` // 32-chars lowercase and digits
+	TokenType    string   `json:"TokenType"`    // "Bearer"
+	Scopes       []string `json:"Scopes"`       // should be [] for our usage
+	UID          string   `json:"UID"`          // 32-chars lowercase and digits
+	LocalID      uint     `json:"LocalID"`      // 0 in my case
+}
+
+type cookiesRequest struct {
```
Comment (qdm12) [inline internal/provider/protonvpn/updater/types.go]: move these to api.go

File: go.mod [hunk 4]
```diff
@@ -50,10 +56,11 @@ require (
 	github.com/qdm12/goservices v0.1.0 // indirect
 	github.com/riobard/go-bloom v0.0.0-20200614022211-cdc8013cb5b3 // indirect
 	github.com/vishvananda/netns v0.0.4 // indirect
-	golang.org/x/crypto v0.32.0 // indirect
-	golang.org/x/mod v0.21.0 // indirect
-	golang.org/x/sync v0.10.0 // indirect
-	golang.org/x/tools v0.26.0 // indirect
```
Comment (qdm12) [inline go.mod]: We should update these first separately to make sure it doesn't break anything.

**Comment by kubrickfr** [comment]
Hi @qdm12,

Thanks for doing this, I'll try it out!

FYI I had also reached out to their support, as a paying customer. And they politely told me to F off.

> Since this decision was purposefully made with the intention to stop such activities due to security concerns, I am afraid I would not be able to provide further support.

So yes, I also got mad at them.

I also abandoned this track because I think it's a security issue to have my unscoped credentials in gluetun configuration: this username / password can be used to access my emails, drive documents, etc.

So I actually made a fork that loads the logicals.json from a local file.

My last response to them was:
> That's fine. I guess we'll just end up having someone maintain a mirror somewhere, and everybody loses.

To which they replied:
> Thank you for your understanding and consideration.

So here we are.

**Comment by qdm12** [comment]
> I also abandoned this track because I think it's a security issue to have my unscoped credentials in gluetun configuration: this username / password can be used to access my emails, drive documents, etc.

I see your point, although code is open source so risk should be limited, but yes still possible. And not everyone has the time to check the code on every commit 😄 !
But at least I can update it (done here) on the master branch for the built-in servers.json.
Actually @shwoop floated the idea on #2919 to have CI update periodically all the servers data. In that case, I can set my credentials as CI secrets to update it as well. That would resolve this situation 👍 Coming soon ™️ I hope!
One last note: you could also create another "dummy" proton free account to access the servers data, if you want to do update servers locally without risk (what I've done for testing).

> So here we are.

Laughing with you in support hell! 😈

**Comment by kubrickfr** [comment]
>although code is open source so risk should be limited

@qdm12 I didn't mean it this way, I don't distrust gluetun, all I'm saying is, I'm not happy leaving my (unencrypted) credentials on my server.

> create another "dummy" proton free account to access the servers data

good suggestion

**Comment by qdm12** [comment]
Oh no worry, I get you as well! Definitely a risk either way (on the server, or in Gluetun or both) - plus right now otp support isn't implemented (and would be cumbersome to use in a container periodically anyway), so disabling otp temporarily does suck too.

File: go.mod (hunk 4 above)
Comment (qdm12) [reply go.mod]: This is ongoing on the master branch, I'm waiting to see if issues are reported

**Comment by n0de0ne** [comment]
How can I test the update ? I'm on tag pr2878 but I don't know how to force an update through CLI

**Comment by kubrickfr** [comment]
I tried it, my (new account created just for that purpose) got immediately suspended "due to a potential policy violation." I doubt it's because of this PR, it's probably because I used the same browser and they don't want people to have multiple accounts. But really they like to make the life of their paying customers difficult...

**Comment by qdm12** [comment]
You need to add `-proton-username xxx -proton-password yyy` to the usual update cli command.
Note I did (by accident but that's fine) update the servers data with it on the latest image/master branch.
Note also I'm waiting to have CI take care of servers data updating (through PRs) before merging this. Asking for credentials is quite the stretch to update servers data, whereas everyone would benefit from a throw away account I'll setup.

@kubrickfr really? If that's the case that's almost hilarious. I'm very shared with Proton. Their support and out of the ordinary help is terribly bad. But they also maintain quite a few Go crypto libraries even the Go team gave up on, like openpgp. I did try to not depend on their libraries (aiming at low 3rd party dependencies) but that was such a deep rabbit hole, I couldn't do it. I'm very 50/50 on the hate train here 😅

**Comment by n0de0ne** [comment]
> `-proton-username xxx -proton-password yyy`

Well that's what I tried 

docker run --rm -v /mnt/user/appdata/gluetun:/gluetun qmcgaw/gluetun update -enduser -providers protonvpn -proton-username my username -proton-password mypassword

But I get flag provided but not defined: -proton-username
Usage of update:
  -all
    	Update servers for all VPN providers
  -dns string
    	DNS resolver address to use (default "8.8.8.8")
  -enduser
    	Write results to /gluetun/servers.json (for end users)
  -ip-token string
    	IP data service token (e.g. ipinfo.io) to use
  -maintainer
    	Write results to ./internal/storage/servers.json to modify the program (for maintainers)
  -minratio float
    	Minimum ratio of servers to find for the update to succeed (default 0.8)
  -providers string
    	CSV string of VPN providers to update server data for

**Comment by qdm12** [comment]
This should work (you forgot to specify the image tag I think)

```
docker run --rm -v /mnt/user/appdata/gluetun:/gluetun qmcgaw/gluetun:pr-2878 update -enduser -providers protonvpn -proton-username my-username -proton-password mypassword
```

**Comment by n0de0ne** [comment]
> This should work (you forgot to specify the image tag I think)
> 
> ```
> docker run --rm -v /mnt/user/appdata/gluetun:/gluetun qmcgaw/gluetun:pr-2878 update -enduser -providers protonvpn -proton-username my-username -proton-password mypassword
> ```

Yeah silly me, the tag was incorrect. Now im facing a different issue, my proton username is my email, this leads to an auth error. « Username is respons does not match request username »

Edit: Actually the username is the part before the @ of my email

**Comment by qdm12** [comment]
> Yeah silly me

No problem, pushed a change to auto-trim the domain in case it's set, to make it silly-proof 👍 I love silly reports in a PR ❤️ rather than on the master branch 😅

**Comment by SerhiyRomanov** [comment]
> This should work (you forgot to specify the image tag I think)
> 
> ```
> docker run --rm -v /mnt/user/appdata/gluetun:/gluetun qmcgaw/gluetun:pr-2878 update -enduser -providers protonvpn -proton-username my-username -proton-password mypassword
> ```

Thanks for your work. I've tested and it's works for me

**Comment by Codelica** [comment]
I've been trying to update for an hour now with this command, and am about to take a hostage. (As they also toss captcha and rate limits in after a few requests)  My "username" at Proton is my email address.  Yet using that via the follwing from a clean host (not rate limted or catpcha'd yet):

`docker run --rm -v /storage/docker/gluetun:/gluetun qmcgaw/gluetun:pr-2878 update -enduser -providers protonvpn -proton-username me@domain.com -proton-password xxxxxxxxxxx`

I get...

```
2025-11-17T02:34:20Z INFO creating /gluetun/servers.json with 20738 hardcoded servers
2025-11-17T02:34:20Z INFO updating Protonvpn servers...
2025-11-17T02:34:27Z ERROR updating server information: getting protonvpn servers: authentifying with Proton: getting auth information: username in response does not match request username: expected me@domain.com got
2025-11-17T02:34:27Z INFO Shutdown successful
```

Any guesses?  I've tried with my "display name" for username just for fun but  get the expected "Incorrect login credentials."

I assume others are using their email usernames.

**Edit:** Just to be clear, my Proton username is my work email address.  It is not a @protonmail.com or @proton.me address.  (As  I see some code related to stripping Proton domains from usernames).  I just have a VPN Plus account.

**Comment by scraunt** [comment]
Linking here for visibility https://github.com/qdm12/gluetun/issues/2985



@Codelica 

You could try enclosing your email with single quotes. Since you can create a Proton account any time (maybe not everyone knows this) I have just created an account only used for VPN - no 'external' email required (e.g. I could log into the Protonmail inbox for that account). Obviously this does not help you if you have an account with paid time on already. You might be best off posting in the discussions, or creating a new issue. You will get more visibility there. Best of luck!

**Comment by qdm12** [comment]
@Codelica 

> Edit: Just to be clear, my Proton username is my work email address. It is not a @protonmail.com or @proton.me address. (As I see some code related to stripping Proton domains from usernames). I just have a VPN Plus account.

Ah! I wasn't aware of that. So both using `username` and `username@domain.com` does not fix it I suppose? I have no idea how this could be fixed. On the other hand, the plan is to update protonvpn servers data regularly with CI so you might not have to do this updating that much. Ideally, you should be able to as a fallback though.

On a similar note, my free account does work but an older (~3 years old) paid account gives me:

```
updating server information: getting protonvpn servers: authentifying with Proton: authentifying: HTTP status code not OK: Unprocessable Entity: {"Code":9001,"Error":"For security reasons, please complete CAPTCHA. If you can't pass it, please try updating your app or contact us here: https://proton.me/support/appeal-abuse","Details":{"HumanVerificationToken":"xxxx","HumanVerificationMethods":["captcha"],"Direct":1,"Description":"","Title":"Human Verification","WebUrl":"https://verify.proton.me/?methods=captcha&token=xxxx","ExpiresAt":1763395346}}
```

Ugh I am hating Proton more almost every day....

Please create an issue if it doesn't work, since I'm not notified on this PR anymore so I likely won't see it.

**Comment by Codelica** [comment]
> You could try enclosing your email with single quotes. Since you can create a Proton account any time (maybe not everyone knows this) I have just created an account only used for VPN - no 'external' email required (e.g. I could log into the Protonmail inbox for that account). 

Yep, I've tried most everything. Quoting, removing special chars, etc.  It really comes down to that username check on return.  The free VPN account is confusing to me though, as it requests an email address to use for the account which becomes the username.  That seems like the same situation to me (username = non Proton email address).  I did try it anyway, but got the same results as my paid account.

> Ah! I wasn't aware of that. So both using username and username@domain.com does not fix it I suppose? I have no idea how this could be fixed. On the other hand, the plan is to update protonvpn servers data regularly with CI so you might not have to do this updating that much. Ideally, you should be able to as a fallback though.

That's correct.  I've tried username@domain.com, username, and "display name" just for fun.  It really feels like I may be getting authenticated, but the return value for username is empty/missing when using user@domain.com (which is my username per their UI and being able to login :) )

> On a similar note, my free account does work but an older (~3 years old) paid account gives me:

Lol.. yea, try it a couple more times and you'll feel their rate limits also with a taunting message about how limits are much higher when logged in 😅

**Comment by FlorentLM** [comment]
Hey, has this become mandatory for any ProtonVPN based install, even with WireGuard? Having the password in clear or in a docker secret is a bit of a downgrade in security, isn't it?

Also what about accounts with 2FA enabled?

**Comment by flueflacks** [comment]
> The free VPN account is confusing to me though, as it requests an email address to use for the account which becomes the username.

having created only a vpn acccount,  My non proton email  i signed up with was my username for login,  until i  added protonmail,  then my proton email was myprotonaddy@proton.me  and my username for logging in and for the updater became  myprotonaddy,  and the updater worked.
